Plat 5595
crowdbotics/modules pull request #103
Opened 2021-08-30 14:42 UTC by santoshpy

## Ticket

PLAT-5595
_Related tickets:_ [PLAT-5595](https://crowdbotics.atlassian.net/browse/PLAT-5595)
_Related PRs:_

## Type of PR

- [ ] Bugfix
- [X] New feature
- [ ] Minor changes

## Changes introduced

Manage the folder structure for backend and mobile scaffold. 
Update README.md file for consistency 

## Test and review

AS this PR is related to PLATFORM-DASHBOARD to test it, Need to merge all related PR.

2021-09-06 16:41 UTC, danielsousaio reviewed
Please consider the related review on [crowdbotics/django-scaffold](https://github.com/crowdbotics/django-scaffold/pull/248#pullrequestreview-747356162).

2021-09-06 16:48 UTC, danielsousaio commented on dist/cookie/{{cookiecutter.project_slug}}/README.md
> +
Should this read `/mobile`?

2021-12-14 09:34 UTC, mabdullahabid commented on dist/raw/ProjectName/README.md
> +# {{cookiecutter.project_slug}}
@danielsousaio would changing the ProjectName to cookiecutter slug work here? I don't think so. Can you confirm?

2021-12-14 09:43 UTC, mabdullahabid commented on scaffold/template/custom/README.md
> +# {{cookiecutter.project_slug}}
@danielsousaio same here

2021-12-14 09:45 UTC, mabdullahabid requested changes
The logic for using the mobile folder and handle all subsequent actions after in `scaffold/install.js` looks okay to me. However, I am not able to review the correctness of the syntax of this JavaScript file.

@danielsousaio can you confirm if this looks good?

@santoshpy There are merge conflicts (which is expected) so maybe you should merge master into this branch and then handle conflicts accordingly.

2021-12-28 15:12 UTC, driverdan commented
@santoshpy Please fix the merge conflicts

2023-10-10 10:58 UTC, danielsousaio commented
Closing stale PR

2023-10-10 10:58 UTC, closed without merging