PLAT-5707: App Store build on new scaffold (modules)
crowdbotics/modules pull request #122
Opened 2021-09-20 16:50 UTC by tan-duong

## Ticket

PLAT-5707

## Type of PR

- [ ] Bugfix
- [ ] New feature
- [x] Minor changes

## Changes introduced

- App Store builds on the new scaffold (modules)

## Test and review

- create app
- deploy ios build

2021-09-20 16:54 UTC, tan-duong commented
@danielsousaio may you please help review and run the command to distribute the change to order places?

2021-09-20 17:17 UTC, driverdan requested changes
The files in `dist` shouldn't be edited directly. You'll need to update the files in `/scaffold/template/custom`.

2021-09-20 18:33 UTC, danielsousaio approved these changes
Looks good

2021-09-21 16:58 UTC, driverdan approved these changes

2021-09-21 16:58 UTC, merged