screen-recording-memo Added
crowdbotics/modules pull request #461
Opened 2022-08-07 18:23 UTC by shahzaib3120

## Ticket

PLAT-XXXX
_Related tickets:_
_Related PRs:_

## Type of PR

- [ ] Bugfix
- [ ] New feature
- [ ] Minor changes

## Changes introduced

_Describe the changes being introduced in this PR_
_Include screenshots if necessary_
_Please link any documentation reference that relate to the changes_

## Test and review

_Describe how a reviewer should test your PR_

2022-08-07 18:24 UTC, shahzaib3120 commented
![preview](https://user-images.githubusercontent.com/50596057/183305503-22c52f88-06bb-4d7d-b2f5-fcf756fd7d4a.png)

2022-08-09 08:20 UTC, saad-abid-crowdbotics requested changes
Move inline styling to the stylesheet.

2022-08-09 08:20 UTC, saad-abid-crowdbotics commented on modules/screen-recording-memo/index.js
> +            }}
Move inline styling to the stylesheet.

2022-08-10 06:39 UTC, saad-abid-crowdbotics approved these changes

2022-08-10 21:46 UTC, shahraizali approved these changes

2022-08-10 21:46 UTC, merged