screen-social-followers Added
crowdbotics/modules pull request #467
Opened 2022-08-07 18:38 UTC by shahzaib3120

## Ticket

PLAT-XXXX
_Related tickets:_
_Related PRs:_

## Type of PR

- [ ] Bugfix
- [ ] New feature
- [ ] Minor changes

## Changes introduced

_Describe the changes being introduced in this PR_
_Include screenshots if necessary_
_Please link any documentation reference that relate to the changes_

## Test and review

_Describe how a reviewer should test your PR_

2022-08-07 18:39 UTC, shahzaib3120 commented
![preview](https://user-images.githubusercontent.com/50596057/183306024-5b367f82-acd5-488b-8b07-863149c7de01.png)

2022-08-09 07:43 UTC, saad-abid-crowdbotics commented on modules/screen-social-followers/index.js
> +            }}
Move inline styling to the stylesheet.

2022-08-09 07:44 UTC, saad-abid-crowdbotics requested changes
Move inline styling to the stylesheet.

2022-08-10 06:28 UTC, saad-abid-crowdbotics approved these changes

2022-08-10 21:44 UTC, shahraizali approved these changes

2022-08-10 21:44 UTC, merged