screen-location-search added
crowdbotics/modules pull request #651
Opened 2022-09-25 23:38 UTC by shahzaib3120

## Ticket

PLAT-XXXX
_Related tickets:_
_Related PRs:_

## Type of PR

- [ ] Bugfix
- [ ] New feature
- [ ] Minor changes

## Changes introduced

_Describe the changes being introduced in this PR_
_Include screenshots if necessary_
_Please link any documentation reference that relate to the changes_

## Test and review

_Describe how a reviewer should test your PR_

2022-09-25 23:38 UTC, shahzaib3120 commented
![preview](https://user-images.githubusercontent.com/50596057/192170736-c8d60485-994f-4bb2-abff-f54f519560bf.png)

2022-10-08 13:29 UTC, shahraizali approved these changes

2022-12-07 17:40 UTC, danielsousaio requested changes

2022-12-07 17:40 UTC, danielsousaio commented on modules/screen-location-search/index.js
> +              thumbColor={useMyLocation ? "#000" : "#000"}
Shouldn't this simply be the color? The ternary has no effect

2023-08-24 14:54 UTC, danielsousaio approved these changes

2023-08-24 14:54 UTC, merged