screen-meetings-list added
crowdbotics/modules pull request #652
Opened 2022-09-25 23:40 UTC by shahzaib3120

## Ticket

PLAT-XXXX
_Related tickets:_
_Related PRs:_

## Type of PR

- [ ] Bugfix
- [ ] New feature
- [ ] Minor changes

## Changes introduced

_Describe the changes being introduced in this PR_
_Include screenshots if necessary_
_Please link any documentation reference that relate to the changes_

## Test and review

_Describe how a reviewer should test your PR_

2022-09-25 23:40 UTC, shahzaib3120 commented
![preview](https://user-images.githubusercontent.com/50596057/192170800-d56d684a-6c95-4696-af4b-4f870946e4b7.png)

2022-10-08 13:31 UTC, shahraizali submitted a review, later dismissed

2022-12-07 17:38 UTC, danielsousaio requested changes

2022-12-07 17:38 UTC, danielsousaio commented on modules/screen-meetings-list/index.js
> +      // backgroundColor: "#" + Math.floor(Math.random() * 16777215).toString(16)
could you remove this commented line please?

2022-12-07 17:38 UTC, danielsousaio commented on modules/screen-meetings-list/index.js
> +  const [seacrhText, setSearchText] = useState("");
```suggestion
  const [searchText, setSearchText] = useState("");
```

2022-12-07 17:38 UTC, danielsousaio commented on modules/screen-meetings-list/index.js
> +        value={seacrhText}
```suggestion
        value={searchText}
```

2023-08-24 14:52 UTC, danielsousaio approved these changes

2023-08-24 14:52 UTC, merged