Booking Module (Backend): Optimization for enterprise
crowdbotics/modules pull request #740
Opened 2022-12-08 16:18 UTC by saad-abid-crowdbotics

## Django booking

## Type of PR

- [ ] Bugfix
- [x] New feature
- [ ] Minor changes

## Running the demo

Django modules specific checks:

- [x] `python manage.py show_urls` shows that the module's urls are resolved correctly
- [x] I have checked that the migrations are detected and run correctly
- [x] I have checked that the admin is working correctly for the module

## Changes introduced

Django booking module integration

## Test and review

1. Create a cart on shopify
2. Add line_items to the shopify cart
3. Retrieve cart data from shopify
4. Save cart data on DB
5. Create a customer booking
6. Add plans for the custom booking
7. Add penalties for the booking

2023-08-21 16:35 UTC, shahraizali requested changes

2023-08-21 16:35 UTC, shahraizali commented on modules/django-booking/django_booking/booking/viewsets.py
> +            req = requests.post(os.environ.get("SHOPIFY_STORE_URL", "") + '/api/2022-10/graphql.json/', json=payload,
move these to separate shopify services/service file

2023-08-21 16:35 UTC, shahraizali commented on modules/django-booking/meta.json
> +}
change preview image

2023-08-25 14:17 UTC, cbshoaib approved these changes
LGTM

2023-08-28 14:02 UTC, merged