Django S3 File-uploader
crowdbotics/modules pull request #774
Opened 2023-01-04 14:25 UTC by saad-abid-crowdbotics

## Django S3 File-uploader

## Type of PR

- [ ] Bugfix
- [x] New feature
- [ ] Minor changes

## Review checklist for new or updated modules

- [x] I have included a `meta.json` file in the module's root directory
- [x] I have included a `preview.png` image in the module's root directory

Django modules specific checks:

- [x] `python manage.py show_urls` shows that the module's urls are resolved correctly
- [x] I have checked that the migrations are detected and run correctly
- [x] I have checked that the admin is working correctly for the module

## Changes introduced

Django S3 File-uploader module integration

## Test and review

1. Create an amazon s3 bucket
2. Display list of amazon s3 buckets
3. Upload a file in an amazon s3 bucket
4. Download a file from an amazon s3 bucket
5. Delete a file from the s3 bucket
6. Generate a Presigned URL for s3 object/file

2023-08-21 16:38 UTC, shahraizali requested changes

2023-08-21 16:38 UTC, shahraizali commented on modules/django-s3-file-uploader/meta.json
> +}
update preview image

2023-08-23 14:48 UTC, danielsousaio approved these changes

2023-08-23 14:48 UTC, danielsousaio approved these changes

2023-08-23 14:49 UTC, merged