Upgrade and Fix: React Native Maps (0.71.7)
crowdbotics/modules pull request #855
Opened 2023-03-29 11:51 UTC by cbshoaib

#  Updated-Readme: React Native Maps

## Type of PR

- [ ] Bugfix
- [ ] New feature
- [x] Minor changes

## Changes introduced
added module dependencies installation setup and scope features in README.md file.

2023-04-11 20:43 UTC, alaisgomes approved these changes

2023-06-19 14:56 UTC, danielsousaio requested changes
The install section can be removed. More details below.

2023-06-19 14:56 UTC, danielsousaio commented on modules/react-native-maps/README.md
> +All the required packages are given in the `package.json` file. Make sure all the dependencies are installed before using this module. Copy all the packages from the `dependencies` and `x-dependencie
> Copy all the packages from the `dependencies` and `x-dependencies` section and past them in your project's main `package.json` file.

Our platform already does this, users don't have to do it manually.

2023-06-19 14:56 UTC, danielsousaio commented on modules/react-native-maps/README.md
> +"prop-types": "15.8.1"
Same here, our platform already installs dependencies.

2023-08-25 15:49 UTC, saad-abid-crowdbotics approved these changes
LGTM.

2023-08-28 13:54 UTC, danielsousaio approved these changes

2023-08-28 13:54 UTC, merged